version: "2.2"
services:
  rabbit:
    image: "rabbit"
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
  queue-db:
    image: "queue_db"
    ports:
      - "5432:5432"
    restart: always
  queue:
    depends_on:
      queue-db:
        condition: "service_healthy"
      rabbit:
        condition: "service_healthy"
    image: "queue"
    stdin_open: true
    tty: true
    restart: always
