version: "2.1"
services:
  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
  queue-db:
    image: "queue_db"
    ports:
      - "5432:5432"
    restart: always
#  nginx-library:
#    image: nginx_router
#    ports:
#      - 4000:80
#    restart: always
